Update compileMyLatex.yml

diff --git a/.github/workflows/compileMyLatex.yml b/.github/workflows/compileMyLatex.yml
--- a/.github/workflows/compileMyLatex.yml
+++ b/.github/workflows/compileMyLatex.yml
@@ -133,39 +133,39 @@ jobs:
           for (( i=0; i<${#warnErrArr[@]}; i++ )); do
              line="${warnErrArr[$i]}"
              echo '134===================> line $line"
-             if [[ "$(echo "$line" | grep -q -E "on input line [0-9]")$?" == 0 ]]; then
-                linenum=$(echo $line | sed -r 's/^.*on input line ([0-9][0-9]*).*/\1/')
-                blanks="$(echo "$line" | sed -r 's/ZZ/ /g')"
-                if [[ "$(echo "$line" | grep -q -E "LaTeX Error")$?" == 0 ]]; then
-                    tmp="$linenum-ERROR-$blanks" 
-                elif [[ "$(echo "$line" | grep -q -E "natbib")$?" == 0 ]]; then
-                    tmp="$linenum-BIB-$blanks"
-                else
-                    tmp="$linenum-WARNING-$blanks"
-                fi
-             elif [[ "$(echo "$line" | grep -q -E "^\.\/${{ github.event.inputs.file2compile }}.tex\:[0-9][0-9]*\:")$?" == 0 ]]; then
-                linenum=$(echo $line | sed -r 's/^\.\/[^:]*\:([0-9][0-9]*).*/\1/')
-                blanks="$(echo "$line" | sed -r 's/ZZ/ /g')"
-                if [[ "$(echo "$line" | grep -q -E "LaTeX Error")$?" == 0 ]]; then
-                    tmp="$linenum-ERROR-$blanks" 
-                elif [[ "$(echo "$line" | grep -q -E "natbib")$?" == 0 ]]; then
-                    tmp="$linenum-BIB-$blanks"
-                else
-                    tmp="$linenum-WARNING-$blanks"
-                fi
-             else
-                blanks="$(echo "$line" | sed -r 's/ZZ/ /g')"
-                if [[ "$(echo "$line" | grep -q -E "LaTeX Error")$?" == 0 ]]; then
-                    tmp="0-ERROR-$blanks" 
-                elif [[ "$(echo "$line" | grep -q -E "natbib")$?" == 0 ]]; then
-                    tmp="0-BIB-$blanks"
-                else
-                    tmp="0-WARNING-$blanks"
-                fi
-             fi
-             echo " "
-             echo " 166 ==============================>>>>>>> tmp: $tmp"
-             warnErrArr[$i]="$tmp"
+             #if [[ "$(echo "$line" | grep -q -E "on input line [0-9]")$?" == 0 ]]; then
+             #   linenum=$(echo $line | sed -r 's/^.*on input line ([0-9][0-9]*).*/\1/')
+             #   blanks="$(echo "$line" | sed -r 's/ZZ/ /g')"
+             #   if [[ "$(echo "$line" | grep -q -E "LaTeX Error")$?" == 0 ]]; then
+             #       tmp="$linenum-ERROR-$blanks" 
+             #   elif [[ "$(echo "$line" | grep -q -E "natbib")$?" == 0 ]]; then
+             #       tmp="$linenum-BIB-$blanks"
+             #   else
+             #       tmp="$linenum-WARNING-$blanks"
+             #   fi
+             #elif [[ "$(echo "$line" | grep -q -E "^\.\/${{ github.event.inputs.file2compile }}.tex\:[0-9][0-9]*\:")$?" == 0 ]]; then
+             #   linenum=$(echo $line | sed -r 's/^\.\/[^:]*\:([0-9][0-9]*).*/\1/')
+             #   blanks="$(echo "$line" | sed -r 's/ZZ/ /g')"
+             #   if [[ "$(echo "$line" | grep -q -E "LaTeX Error")$?" == 0 ]]; then
+             #       tmp="$linenum-ERROR-$blanks" 
+             #   elif [[ "$(echo "$line" | grep -q -E "natbib")$?" == 0 ]]; then
+             #       tmp="$linenum-BIB-$blanks"
+             #   else
+             #       tmp="$linenum-WARNING-$blanks"
+             #   fi
+             #else
+             #   blanks="$(echo "$line" | sed -r 's/ZZ/ /g')"
+             #   if [[ "$(echo "$line" | grep -q -E "LaTeX Error")$?" == 0 ]]; then
+             #       tmp="0-ERROR-$blanks" 
+             #   elif [[ "$(echo "$line" | grep -q -E "natbib")$?" == 0 ]]; then
+             #       tmp="0-BIB-$blanks"
+             #   else
+             #       tmp="0-WARNING-$blanks"
+             #   fi
+             #fi
+             #echo " "
+             #echo " 166 ==============================>>>>>>> tmp: $tmp"
+             #warnErrArr[$i]="$tmp"
           done
           echo " "
           echo " "
