Update compileMyLatex.yml

diff --git a/.github/workflows/compileMyLatex.yml b/.github/workflows/compileMyLatex.yml
--- a/.github/workflows/compileMyLatex.yml
+++ b/.github/workflows/compileMyLatex.yml
@@ -186,12 +186,12 @@ jobs:
             echo "      none" >> tout.txt
           fi
           while  [ $error != "" ]; do
-            linenum=$(echo "$error" | sed -r 's/^([0-9][0-9]*)-.*/\1/')
+            linenum=$(echo "$error" | sed -r 's/^([0-9][0-9]*)\-.*/\1/')
             if [[ $linenum > 0 ]]; then
                # look for all occurances of this line number in the error/warning list
                for (( i=0; i<${#sorted[@]}; i++ )); do
                   if [[ "$(echo "${sorted[$i]}" | grep -q -E "^$linenum-")$?" == 0 ]]; then
-                     line="$(echo "${sorted[$i]}" | sed -r 's/^[0-9][0-9]*-[A-Z]-[A-Z]*-//' | sed -r 's/ZZ/ /g')"
+                     line="$(echo "${sorted[$i]}" | sed -r 's/^[0-9][0-9]*\-[A-Z][A-Z]*\-//' | sed -r 's/ZZ/ /g')"
                      echo $line >> tout.txt
                      # remove this item from the list
                      unset sorted[$i]
@@ -205,7 +205,7 @@ jobs:
                echo "205"
                for (( i=0; i<${sorted[@]}; i++ )); do
                   if [[ "${sorted[$i]}" =~ "$error" ]]; then
-                     line="$(echo "${sorted[$i]}" | sed -r 's/^[0-9][0-9]*-[A-Z]-[A-Z]*-//' | sed -r 's/ZZ/ /g')"
+                     line="$(echo "${sorted[$i]}" | sed -r 's/^[0-9][0-9]*\-[A-Z][A-Z]*\-//' | sed -r 's/ZZ/ /g')"
                      echo "there is a match, here it is:"
                      echo "$line"
                      echo $line >> tout.txt
@@ -220,47 +220,38 @@ jobs:
             for (( i=0; i<${#sorted[@]}; i++ )); do
                line="${sorted[$i]}"
                if [[ "$line" =~ "-ERROR-" ]]; then
-                  error=$line
+                  error="$line"
                   break
                fi
             done
             echo "-------------------------------------------------------------------------" >> tout.txt
           done
-          echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
-          cat tout.txt
-          echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
           echo "" >> tout.txt
-          #echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
-          #echo "              WARNINGS IN ${{  github.event.inputs.file2compile }}.tex" >> tout.txt
-          #echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
+          echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
+          echo "              WARNINGS IN ${{  github.event.inputs.file2compile }}.tex" >> tout.txt
+          echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
           warning=""
-          echo " "
-          echo " "
-          printf '%s\n' "${sorted[@]}"
-          echo " " 
-          echo " "
           for (( i=0; i<${#sorted[@]}; i++ )); do
             line="${sorted[$i]}"
-            echo "seein if this line has WARNING in it"
-            echo "$line"
             if [[ "$line" =~ "-WARNING-" ]]; then
                warning="$line"
                break
             fi
           done
-          echo "warning is: $warning"
+          echo "warning is:"
+          echo "$warning"
           # if there were no warnings, then put 'none'
           if [ $warning = "" ]; then
             echo "      none" >> tout.txt
           fi
           while  [ $warning != "" ]; do
-            linenum=$(echo "$warning" | sed -r 's/^([0-9][0-9]*)-.*/\1/')
+            linenum=$(echo "$warning" | sed -r 's/^([0-9][0-9]*)\-.*/\1/')
             echo "line num $linenum"
             if [[ $linenum > 0 ]]; then
                # look for all occurances of this line number in the error/warning list
                for (( i=0; i<${#sorted[@]}; i++ )); do
-                  if [[ "$(echo "${sorted[$i]}" | grep -q -E "^$linenum-")$?" == 0 ]]; then
-                     line="$(echo "${sorted[$i]}" | sed -r 's/^[0-9][0-9]*-[A-Z]-[A-Z]*-//' | sed -r 's/ZZ/ /g')"
+                  if [[ "$(echo "${sorted[$i]}" | grep -q -E "^$linenum\-")$?" == 0 ]]; then
+                     line="$(echo "${sorted[$i]}" | sed -r 's/^[0-9][0-9]*\-[A-Z][A-Z]*\-//' | sed -r 's/ZZ/ /g')"
                      echo $line >> tout.txt
                      # remove this item from the list
                      unset sorted[$i]
@@ -275,7 +266,7 @@ jobs:
                # look up where this line is in the list and remove it from the list
                for (( i=0; i<${sorted[@]}; i++ )); do
                   if [[ "${sorted[$i]}" =~ "$warning" ]]; then
-                     line="$(echo "${sorted[$i]}" | sed -r 's/^[0-9][0-9]*-[A-Z]-[A-Z]*-//' | sed -r 's/ZZ/ /g')"
+                     line="$(echo "${sorted[$i]}" | sed -r 's/^[0-9][0-9]*\-[A-Z][A-Z]*\-//' | sed -r 's/ZZ/ /g')"
                      echo "no line number in this one: $line"
                      echo $line >> tout.txt
                      # remove from list
