Update compileMyLatex.yml

diff --git a/.github/workflows/compileMyLatex.yml b/.github/workflows/compileMyLatex.yml
--- a/.github/workflows/compileMyLatex.yml
+++ b/.github/workflows/compileMyLatex.yml
@@ -117,41 +117,50 @@ jobs:
              if [[ "$(echo "$line" | grep -q -E "on input line [0-9]")$?" == 0 ]]; then
                 linenum=$(echo $line | sed -r 's/^.*on input line ([0-9]*).*/\1/')
                 echo $linenum__$line >> warnerr.txt
-                echo "linenum2 exists:  $linenum"
              elif [[ "$(echo "$line" | grep -q -E "^\.\/${{ github.event.inputs.file2compile }}.tex\:[0-9]*\:")$?" == 0 ]]; then
                 linenum=$(echo $line | sed -r 's/^\.\/[^:]*\:([0-9]*).*/\1/')
                 echo $linenum__$line >> warnerr.txt
-                echo "linenum1 exists .... $linenum"
              else
                 echo noPage__$line >> warnerr.txt
-                echo "neither linenum1 nor linenum2"
              fi
           done < warningError.txt
-          done < warningError.txt
+          mv -f warnerr.txt warningError.txt
+          sort warningError.txt | uniq > warnerr.txt
+          mv -f warnerr.txt warningError.txt
           echo " "
           echo " "
-          #cat warnerr.txt
+          cat warnerr.txt
           # The below pulls out only those lines that are directly related to warnings and errors within the .tex file 
           # This step is why we needed everything related to a given error to appear in a single line and did the formatting above.
           # https://stackoverflow.com/questions/75534451/using-grep-output-as-pattern-for-a-second-grep
           # need to go line by line to consolidate all items associated with the same line
-          grep -i 'error' warningError.txt > error.txt || touch errtmp.txt 
-          sort errtmp.txt | uniq > errors.txt
-          rm -f tmptmp.txt
           ## https://stackoverflow.com/questions/57788813/grep-return-0-if-no-match
           ## squash.io/extracting=numbers-from-strings-in-bash
           ## https://stackoverflow.com/questions/17883661/how-to-extract-numbers-from-a-string
           ## https://stackoverflow.com/questions/2624300/save-part-of-matching-pattern-to-variable
-          #while IFS= read -r line; do
-          #  echo $line >> tout.txt
-          #done < compileout.txt
-          #  linenum=$(echo $line | sed 's/^.*: \([0-9]*\):.*/\1/')
-          #  head -n $linenum ${{ github.event.inputs.file2compile }}.tex | tail -1 >> tout.txt
-          #  echo "-------------------------------------------------------------------------" >> tout.txt
-          #done < errors.txt
           echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
           echo "              ERRORS IN ${{  github.event.inputs.file2compile }}.tex" >> tout.txt
           echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
+          grep -E "LaTeX Error" warningError.txt >> errors.txt
+          while IFS= read -r line; do
+            echo $line | sed 's/^[0-9]*//' >> tout.txt
+            linenum=$(echo $line | sed 's/^\([0-9]*)__\.*/\1/')
+            # look for other occurances of this error in the file 
+            if [[ "$(echo "$line" | grep -q -E "^$linenum__LaTeX Warning")$?" == 0 ]]; then
+               touch tmp.txt && echo "$line" | grep -E "^$linenum__LaTeX Warning" >> tmp.txt
+               while IFS= read -r ln; do
+                  echo $line | sed 's/^[0-9]*//' >> tout.txt
+                  #  PUT A WORD IN FRONT OF LINE SO IT WONT BE PROCESSED AGAIN
+
+
+                  
+               done < tmp.txt
+            fi
+            # now get the line number from the latex file itself
+            head -n $linenum ${{ github.event.inputs.file2compile }}.tex | tail -1 >> tout.txt
+          #  echo "-------------------------------------------------------------------------" >> tout.txt
+          done < errors.txt
+
           echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
           echo "              WARNINGS IN ${{  github.event.inputs.file2compile }}.tex" >> tout.txt
           echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
