Update compileMyLatex.yml

diff --git a/.github/workflows/compileMyLatex.yml b/.github/workflows/compileMyLatex.yml
--- a/.github/workflows/compileMyLatex.yml
+++ b/.github/workflows/compileMyLatex.yml
@@ -170,13 +170,15 @@ jobs:
           while IFS= read -r line; do
             echo "line being looked at: $line"
             # determine if this line has already been written. If not, then proceed
-            echo " how many lines found?"
-            echo "$(cat tout.txt | grep -q -E "$line")$?"
-            if [[ "$(grep -c $line tout.txt)" == 0 ]]; then
+            if [[ "$(cat tout.txt | grep -q -E "$line")$?" == 0 ]]; then
               echo $line | sed 's/^[0-9][0-9]* [A-Z][A-Z]* //' >> tout.txt
               linenum=$(echo $line | sed 's/^\([0-9][0-9]*)\.*/\1/')
               # remove this line from warningError.txt
               sed -i "/$line/d" warningError.txt
+              echo " how many lines found? (should show 0 if working properly)"
+              echo "$(cat warningError.txt | grep -q -E "$line")$?"
+              echo " the below should be 0 if working properly"
+              echo "$(cat tout.txt | grep -q -E "$line")$?"
               if [[ $linenum > 0 ]]; then
                  # look for other occurances of this line number in the file
                  touch tmp.txt && grep -E "^$linenum " warningError.txt >> tmp.txt
