Update compileMyLatex.yml

diff --git a/.github/workflows/compileMyLatex.yml b/.github/workflows/compileMyLatex.yml
--- a/.github/workflows/compileMyLatex.yml
+++ b/.github/workflows/compileMyLatex.yml
@@ -148,7 +148,7 @@ jobs:
            "compileOut.txt*","$CORENAME.aux","$CORENAME.bbl","$CORENAME.blg","$CORENAME.fdb_latexmk", \
            "$CORENAME.fls","$CORENAME.out","$CORENAME.sync*","$CORENAME.synctex.gz","doesNotUsePruned.txt","errout.txt*","fin.txt", \
            "$FULLLOG","html.txt","$HTMLFILE","inpaperCites.txt","$LOG","$OUTFILE","$PDFFILE","$PDFHIRES", \
-           "$STARTFILE","thereAreErrors.txt","tout.txt","usedBibfile.txt","warnout.txt" \
+           "$STARTFILE","usedBibfile.txt","warnout.txt" \
            )
            for (( i=0; i<${#filelist[@]}; i++ )); do
              if [ hashFiles("${filelist[$i]}") ]; then
@@ -394,10 +394,10 @@ jobs:
     steps:
       - name: Capture full compilation output
         run: |
+           fatalErrors=false
            fileliststr=''
            # ....... if the pdf file was generated, then the errors must have NOT been fatal.
-           rm -f noFatalErrors.txt
-           if [[ "$( -Eq "output to '${PDFFILE}'" compileOut.txt)$?" == 0 ]]; then touch noFatalErrors.txt; fi
+           if [[ "$( -Eq "output to '${PDFFILE}'" compileOut.txt)$?" == 0 ]]; then fatalErrors=true; fi
            # ....... prepare the compilation log for processing by first removing all end-of-line characters
            touch errout.txt
            # ....... just to be safe, remove all \a, \t and \x0 because we use these as special markers later
@@ -444,14 +444,13 @@ jobs:
            rm -f tmp.txt
            cat errout.txt | sort -r -t- -g -k1,1n -k2 -s | uniq | sed -r 's/\a/ /g' > tmp.txt
            mv -f tmp.txt errout.txt
-        continue-on-error: true
-        #
-      - name: Process the errors and warnings
-        # remove lines in the output that are unrelated to the latex compilation itself
-        run: |
+           #
+           # ==========================================================
+           # remove lines in the output that are unrelated to the latex compilation itself
+           # ==========================================================
            readarray -t sorted < errout.txt
            #  #######################   START CONSOLIDATING THE ERRORS ###################
-           rm -f thereAreErrors.txt
+           rm -f tout.txt
            touch tout.txt
            errtypes=("ERROR" "WARNING" "BIB")
            banners=("FATAL ERRORS" "WARNINGS" "CITATION ISSUES")
@@ -463,9 +462,7 @@ jobs:
               for (( j=0; j<${#sorted[@]}; j++ )); do
                   if [[ "${sorted[$j]}" =~ "-${errtypes[$i]}-" ]]; then 
                      issue="${sorted[$j]}"
-                     if [[ "${errtypes[$i]}" =~ "ERROR" ]]; then touch thereAreErrors.txt; fi
-                     # if a pdf file was generated by the compiler, then consider the errors to not be fatal.
-                     if [[ hashFiles(noFatalErrors.txt) ]]; then rm -f thereAreErrors.txt; fi
+                     if [[ "${errtypes[$i]}" =~ "ERROR" ]]; then fatalErrors=true; fi
                      break;
                   fi
               done
@@ -506,6 +503,7 @@ jobs:
               done
               echo " " >> tout.txt
            done
+           echo "FATALERRORS=$fatalErrors" >> $GITHUB_ENV
         continue-on-error: true
         #
       - name: Gather up list of references
@@ -534,7 +532,7 @@ jobs:
         continue-on-error: true
         #
       - name: Convert errors to html file
-        if: ${{ always() && hashFiles('thereAreErrors.txt') }}
+        if: ${{ always() && fatalErrors }}
         run: |
            # determine if there were no errors, meaning that errors.txt is empty file. If so, place the word none under the
            # banner of this section in output file. But if there were errors, then remove the pdf file so that the pdf file
@@ -600,7 +598,7 @@ jobs:
       #
     steps:
       - name: update START status file if compilation successful
-        if: ${{ always() && ! hashFiles('thereAreErrors.txt') }}
+        if: ${{ always() && ! ($FATALERRORS) }}
         run: |
            rm -f $STARTFILE
            touch $STARTFILE
@@ -647,7 +645,6 @@ jobs:
            "html.txt",
            "inpaperCites.txt",
            "$LOG",
-           "thereAreErrors.txt",
            "uncompressed.list", \
            "usedBibfile.txt",
            "warnout.txt" \
