Update compileMyLatex.yml

diff --git a/.github/workflows/compileMyLatex.yml b/.github/workflows/compileMyLatex.yml
--- a/.github/workflows/compileMyLatex.yml
+++ b/.github/workflows/compileMyLatex.yml
@@ -231,122 +231,122 @@ jobs:
           cat tout.txt
           echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
           echo "" >> tout.txt
-          echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
-          echo "              WARNINGS IN ${{  github.event.inputs.file2compile }}.tex" >> tout.txt
-          echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
-          warnings=""
-          for (( i=0; i<${#sorted[@]}; i++ )); do
-            line="${sorted[$i]}"
-            if [[ "$(echo "$line" | grep -q -E "-WARNING-")$?" == 0 ]]; then
-               warnings="$line"
-               break
-            fi
-          done
-          echo "================================> the warning is $warnings"
-          # if there were no warnings, then put 'none'
-          if [ $warnings -eq "" ]; then
-            echo "      none" >> tout.txt
-          fi
-          while  [ $warnings -ne "" ]; do
-            linenum=$(echo "$warnings" | sed -r 's/^([0-9][0-9]*)-.*/\1/')
-            if [[ $linenum > 0 ]]; then
-               # look for all occurances of this line number in the error/warning list
-               for (( i=0; i<${#sorted[@]}; i++ )); do
-                  if [[ "$(echo "${sorted[$i]}" | grep -q -E "^$linenum-")$?" == 0 ]]; then
-                     line="$(echo "${sorted[$i]}" | sed -r 's/^[0-9][0-9]*-[A-Z]-[A-Z]*-//' | sed -r 's/ZZ/ /g')"
-                     echo $line >> tout.txt
-                     # remove this item from the list
-                     unset sorted[$i]
-                  fi
-               done
-               # now look up the line in the .tex file and place underneath
-               echo "Line #$linenum ----------------------- " >> tout.txt
-               head -n $linenum ${{ github.event.inputs.file2compile }}.tex | tail -1 >> tout.txt
-            else
-               # look up where this line is in the list and remove it from the list
-               for (( i=0; i<${sorted[@]}; i++ )); do
-                  if [[ "${sorted[$i]}" = "$warnings" ]]; then
-                     line="$(echo "${sorted[$i]}" | sed -r 's/^[0-9][0-9]*-[A-Z]-[A-Z]*-//' | sed -r 's/ZZ/ /g')"
-                     echo $line >> tout.txt
-                     # remove from list
-                     unset sorted[$i]
-                  fi
-               done
-            fi
-            sorted=("${sorted[@]}")
-            echo "after removing the now-procesed lines, heres the list"
-            printf '%s\n' "${sorted[@]}"
-            # See if any more errors remain in the list and need to be processed in the next loop iteration
-            warnings=""
-            for (( i=0; i<${#sorted[@]}; i++ )); do
-               line="${sorted[$i]}"
-               if [[ "$(echo $line | grep -q -E "-WARNING-")$?" == 0 ]]; then
-                  warnings=$line
-                  break
-               fi
-            done
-            echo "at the end of the loop, here is the next error: $warnings"
-            echo "-------------------------------------------------------------------------" >> tout.txt
-          done          
-          echo "&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"
-          cat tout.txt
-          echo "&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"
-          echo "" >> tout.txt
-          echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
-          echo "              CITATION ISSUES IN ${{  github.event.inputs.file2compile }}.tex " >> tout.txt
-          echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
-          rm -f biberrs.txt && touch biberrs.txt
-          grep -E "^[0-9][0-9]* BIB " warningError.txt >> biberrs.txt
-          if [ $(wc -c < "biberrs.txt") -eq 0 ]; then
-            echo "      none" >> tout.txt
-          fi
-          while  [ $(wc -c < "biberrs.txt") -gt 0 ]; do
-            line="$(head -1 biberrs.txt)"
-            linenum=$(echo $line | sed -r 's/^([0-9][0-9]*) .*/\1/')
-            if [[ $linenum > 0 ]]; then
-               # look for all occurances of this line number in the file
-               rm -f tmp.txt && touch tmp.txt && grep -E "^$linenum " warningError.txt >> tmp.txt
-               while IFS= read -r ln; do
-                  modLine=$(echo $ln | sed -r 's/^[0-9][0-9]* [A-Z][A-Z]* //')
-                  echo $modLine >> tout.txt
-                  # remove these other lines from warningError.txt
-                  rm -f cp.txt && grep -v "$ln" warningError.txt >> cp.txt && mv -f cp.txt warningError.txt
-               done < tmp.txt
-               # now look up the line in the .tex file and place underneath
-               echo "Line #$linenum ----------------------- " >> tout.txt
-               head -n $linenum ${{ github.event.inputs.file2compile }}.tex | tail -1 >> tout.txt
-            fi
-            # now look for more bib errs
-            rm -f biberrs.txt && touch biberrs.txt
-            grep -E "^[0-9][0-9]* ERROR " warningError.txt >> biberrs.txt
-            echo "-------------------------------------------------------------------------" >> tout.txt
-          done
-          echo "***************************************************************************************"
-          cat tout.txt
-          echo "***************************************************************************************"
-          echo " " 
-          echo " " 
-          echo " "
-          echo "(((((((((((((((((("
-          cat warningError.txt
-          echo "))))))))))))))))))"
-          # https://stackoverflow.com/questions/57788813/grep-return-0-if-no-match
-          # squash.io/extracting=numbers-from-strings-in-bash
-          # https://stackoverflow.com/questions/17883661/how-to-extract-numbers-from-a-string
-          # https://stackoverflow.com/questions/2624300/save-part-of-matching-pattern-to-variable
-          ## determine if there were no errors, meaning that errors.txt is empty file. If so, place
-          ## the word none under the banner of this section in output file. But if there were errors, 
-          ## then remove the pdf file so that the pdf file that gets shown in gooTeX is the compilation errors
-          ## rather than a mangled pdf. 
+          #echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
+          #echo "              WARNINGS IN ${{  github.event.inputs.file2compile }}.tex" >> tout.txt
+          #echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
+          #warnings=""
+          #for (( i=0; i<${#sorted[@]}; i++ )); do
+          #  line="${sorted[$i]}"
+          #  if [[ "$(echo "$line" | grep -q -E "-WARNING-")$?" == 0 ]]; then
+          #     warnings="$line"
+          #     break
+          #  fi
+          #done
+          #echo "================================> the warning is $warnings"
+          ## if there were no warnings, then put 'none'
+          #if [ $warnings -eq "" ]; then
+          #  echo "      none" >> tout.txt
+          #fi
+          #while  [ $warnings -ne "" ]; do
+          #  linenum=$(echo "$warnings" | sed -r 's/^([0-9][0-9]*)-.*/\1/')
+          #  if [[ $linenum > 0 ]]; then
+          #     # look for all occurances of this line number in the error/warning list
+          #     for (( i=0; i<${#sorted[@]}; i++ )); do
+          #        if [[ "$(echo "${sorted[$i]}" | grep -q -E "^$linenum-")$?" == 0 ]]; then
+          #           line="$(echo "${sorted[$i]}" | sed -r 's/^[0-9][0-9]*-[A-Z]-[A-Z]*-//' | sed -r 's/ZZ/ /g')"
+          #           echo $line >> tout.txt
+          #           # remove this item from the list
+          #           unset sorted[$i]
+          #        fi
+          #     done
+          #     # now look up the line in the .tex file and place underneath
+          #     echo "Line #$linenum ----------------------- " >> tout.txt
+          #     head -n $linenum ${{ github.event.inputs.file2compile }}.tex | tail -1 >> tout.txt
+          #  else
+          #     # look up where this line is in the list and remove it from the list
+          #     for (( i=0; i<${sorted[@]}; i++ )); do
+          #        if [[ "${sorted[$i]}" = "$warnings" ]]; then
+          #           line="$(echo "${sorted[$i]}" | sed -r 's/^[0-9][0-9]*-[A-Z]-[A-Z]*-//' | sed -r 's/ZZ/ /g')"
+          #           echo $line >> tout.txt
+          #           # remove from list
+          #           unset sorted[$i]
+          #        fi
+          #     done
+          #  fi
+          #  sorted=("${sorted[@]}")
+          #  echo "after removing the now-procesed lines, heres the list"
+          #  printf '%s\n' "${sorted[@]}"
+          #  # See if any more errors remain in the list and need to be processed in the next loop iteration
+          #  warnings=""
+          #  for (( i=0; i<${#sorted[@]}; i++ )); do
+          #     line="${sorted[$i]}"
+          #     if [[ "$(echo $line | grep -q -E "-WARNING-")$?" == 0 ]]; then
+          #        warnings=$line
+          #        break
+          #     fi
+          #  done
+          #  echo "at the end of the loop, here is the next error: $warnings"
+          #  echo "-------------------------------------------------------------------------" >> tout.txt
+          #done          
+          #echo "&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"
+          #cat tout.txt
+          #echo "&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"
           #echo "" >> tout.txt
           #echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
-          #echo "              LIST OF REFERENCES IN ${{ github.event.inputs.file2compile }}.tex" >> tout.txt
+          #echo "              CITATION ISSUES IN ${{  github.event.inputs.file2compile }}.tex " >> tout.txt
           #echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
-          #grep -e '[eE]rror' -e '[wW]arning' allout.txt > tmptmp1.txt || touch tmptmp1.txt
-          #grep -i ': citation' tmptmp1.txt > tmptmp2.txt || touch tmptmp2.txt
-          #grep -i 'undefined' tmptmp2.txt > tmptmp3.txt || touch tmptmp3.txt
-          #grep -Eo '`[^ ]+' tmptmp3.txt > tmptmp4.txt || touch tmptmp4.txt
-          #cat tmptmp4.txt | sed -r 's/`//g' | sed -r "s/'//g" > tmptmp5.txt
+          #rm -f biberrs.txt && touch biberrs.txt
+          #grep -E "^[0-9][0-9]* BIB " warningError.txt >> biberrs.txt
+          #if [ $(wc -c < "biberrs.txt") -eq 0 ]; then
+          #  echo "      none" >> tout.txt
+          #fi
+          #while  [ $(wc -c < "biberrs.txt") -gt 0 ]; do
+          #  line="$(head -1 biberrs.txt)"
+          #  linenum=$(echo $line | sed -r 's/^([0-9][0-9]*) .*/\1/')
+          #  if [[ $linenum > 0 ]]; then
+          #     # look for all occurances of this line number in the file
+          #     rm -f tmp.txt && touch tmp.txt && grep -E "^$linenum " warningError.txt >> tmp.txt
+          #     while IFS= read -r ln; do
+          #        modLine=$(echo $ln | sed -r 's/^[0-9][0-9]* [A-Z][A-Z]* //')
+          #        echo $modLine >> tout.txt
+          #        # remove these other lines from warningError.txt
+          #        rm -f cp.txt && grep -v "$ln" warningError.txt >> cp.txt && mv -f cp.txt warningError.txt
+          #     done < tmp.txt
+          #     # now look up the line in the .tex file and place underneath
+          #     echo "Line #$linenum ----------------------- " >> tout.txt
+          #     head -n $linenum ${{ github.event.inputs.file2compile }}.tex | tail -1 >> tout.txt
+          #  fi
+          #  # now look for more bib errs
+          #  rm -f biberrs.txt && touch biberrs.txt
+          #  grep -E "^[0-9][0-9]* ERROR " warningError.txt >> biberrs.txt
+          #  echo "-------------------------------------------------------------------------" >> tout.txt
+          #done
+          #echo "***************************************************************************************"
+          #cat tout.txt
+          #echo "***************************************************************************************"
+          #echo " " 
+          #echo " " 
+          #echo " "
+          #echo "(((((((((((((((((("
+          #cat warningError.txt
+          #echo "))))))))))))))))))"
+          ## https://stackoverflow.com/questions/57788813/grep-return-0-if-no-match
+          ## squash.io/extracting=numbers-from-strings-in-bash
+          ## https://stackoverflow.com/questions/17883661/how-to-extract-numbers-from-a-string
+          ## https://stackoverflow.com/questions/2624300/save-part-of-matching-pattern-to-variable
+          ### determine if there were no errors, meaning that errors.txt is empty file. If so, place
+          ### the word none under the banner of this section in output file. But if there were errors, 
+          ### then remove the pdf file so that the pdf file that gets shown in gooTeX is the compilation errors
+          ### rather than a mangled pdf. 
+          ##echo "" >> tout.txt
+          ##echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
+          ##echo "              LIST OF REFERENCES IN ${{ github.event.inputs.file2compile }}.tex" >> tout.txt
+          ##echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
+          ##grep -e '[eE]rror' -e '[wW]arning' allout.txt > tmptmp1.txt || touch tmptmp1.txt
+          ##grep -i ': citation' tmptmp1.txt > tmptmp2.txt || touch tmptmp2.txt
+          ##grep -i 'undefined' tmptmp2.txt > tmptmp3.txt || touch tmptmp3.txt
+          ##grep -Eo '`[^ ]+' tmptmp3.txt > tmptmp4.txt || touch tmptmp4.txt
+          ##cat tmptmp4.txt | sed -r 's/`//g' | sed -r "s/'//g" > tmptmp5.txt
           #sort tmptmp5.txt | uniq >> tout.txt
           #if [ $(wc -c < "tmptmp5.txt") -eq 0 ]; then
           #  echo "      none" >> tout.txt
