Update compileMyLatex.yml

diff --git a/.github/workflows/compileMyLatex.yml b/.github/workflows/compileMyLatex.yml
--- a/.github/workflows/compileMyLatex.yml
+++ b/.github/workflows/compileMyLatex.yml
@@ -110,18 +110,33 @@ jobs:
           # now get the warnings, but note that some of the warnings are actually errors (like figure files that are mispelled) and need to 
           # be consolidated with the associated line in the error section here
           grep -E "^LaTeX Warning\:" ${{ github.event.inputs.file2compile }}_full.log >> warningError.txt
+          # take a look at the bib tex errors
+          grep -E "^Package natbib Warning\: Citation" ${{ github.event.inputs.file2compile }}_full.log >> warningError.txt
           # Now pull out the line number, if provided, in each warning and error
+          cat warningError.txt
           touch warnerr.txt
           while IFS= read -r line; do
              echo $line
              if [[ "$(echo "$line" | grep -q -E "on input line [0-9]")$?" == 0 ]]; then
                 linenum=$(echo $line | sed -r 's/^.*on input line ([0-9]*).*/\1/')
-                echo $linenum__$line >> warnerr.txt
+                if [[ "$(echo "$line" | grep -q -E "LaTeX Error")$?" == 0 ]]; then
+                    echo $linenum__ERROR__$line >> warnerr.txt
+                else
+                    echo $linenum__WARNING__$line >> warnerr.txt
+                fi
              elif [[ "$(echo "$line" | grep -q -E "^\.\/${{ github.event.inputs.file2compile }}.tex\:[0-9]*\:")$?" == 0 ]]; then
                 linenum=$(echo $line | sed -r 's/^\.\/[^:]*\:([0-9]*).*/\1/')
-                echo $linenum__$line >> warnerr.txt
+                if [[ "$(echo "$line" | grep -q -E "LaTeX Error")$?" == 0 ]]; then
+                    echo $linenum__ERROR__$line >> warnerr.txt
+                else
+                    echo $linenum__WARNING__$line >> warnerr.txt
+                fi
              else
-                echo noPage__$line >> warnerr.txt
+                if [[ "$(echo "$line" | grep -q -E "LaTeX Error")$?" == 0 ]]; then
+                    echo 0__ERROR__$line >> warnerr.txt
+                else
+                    echo 0__WARNING__$line >> warnerr.txt
+                fi
              fi
           done < warningError.txt
           mv -f warnerr.txt warningError.txt
@@ -129,48 +144,74 @@ jobs:
           mv -f warnerr.txt warningError.txt
           echo " "
           echo " "
-          cat warnerr.txt
+          cat warningError.txt
           # The below pulls out only those lines that are directly related to warnings and errors within the .tex file 
           # This step is why we needed everything related to a given error to appear in a single line and did the formatting above.
           # https://stackoverflow.com/questions/75534451/using-grep-output-as-pattern-for-a-second-grep
           # need to go line by line to consolidate all items associated with the same line
-          ## https://stackoverflow.com/questions/57788813/grep-return-0-if-no-match
-          ## squash.io/extracting=numbers-from-strings-in-bash
-          ## https://stackoverflow.com/questions/17883661/how-to-extract-numbers-from-a-string
-          ## https://stackoverflow.com/questions/2624300/save-part-of-matching-pattern-to-variable
+          # https://stackoverflow.com/questions/57788813/grep-return-0-if-no-match
+          # squash.io/extracting=numbers-from-strings-in-bash
+          # https://stackoverflow.com/questions/17883661/how-to-extract-numbers-from-a-string
+          # https://stackoverflow.com/questions/2624300/save-part-of-matching-pattern-to-variable
           echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
           echo "              ERRORS IN ${{  github.event.inputs.file2compile }}.tex" >> tout.txt
           echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
-          grep -E "LaTeX Error" warningError.txt >> errors.txt
+          touch errors.txt
+          grep -E "__ERROR__" warningError.txt >> errors.txt
           while IFS= read -r line; do
-            echo $line | sed 's/^[0-9]*//' >> tout.txt
-            linenum=$(echo $line | sed 's/^\([0-9]*)__\.*/\1/')
-            # look for other occurances of this error in the file 
-            if [[ "$(echo "$line" | grep -q -E "^$linenum__LaTeX Warning")$?" == 0 ]]; then
-               touch tmp.txt && echo "$line" | grep -E "^$linenum__LaTeX Warning" >> tmp.txt
-               while IFS= read -r ln; do
-                  echo $line | sed 's/^[0-9]*//' >> tout.txt
-                  #  PUT A WORD IN FRONT OF LINE SO IT WONT BE PROCESSED AGAIN
-
-
-                  
-               done < tmp.txt
+            # determine if this line has already been written. If not, then proceed
+            if [[ "$(grep -c $line tout.txt)" == 0 ]]; then
+              echo $line | sed 's/^[0-9]*__[A-Z]*__//' >> tout.txt
+              linenum=$(echo $line | sed 's/^\([0-9]*)\.*/\1/')
+              # remove this line from warningError.txt
+              sed -i "/$line/d" warningError.txt
+              if [[ $linenum > 0 ]]; then
+                 # look for other occurances of this line number in the file
+                 touch tmp.txt && grep -E "^$linenum__" warningError.txt >> tmp.txt
+                 while IFS= read -r ln; do
+                   echo $ln | sed 's/^[0-9]*__[A-Z]*__//' >> tout.txt
+                   # remove from warningError.txt
+                   sed -i "/$ln/d" warningError.txt
+                 done < tmp.txt
+                 # now look up the line in the .tex file and place underneath
+                 head -n $linenum ${{ github.event.inputs.file2compile }}.tex | tail -1 >> tout.txt
+              fi
+              echo "-------------------------------------------------------------------------" >> tout.txt
             fi
-            # now get the line number from the latex file itself
-            head -n $linenum ${{ github.event.inputs.file2compile }}.tex | tail -1 >> tout.txt
-          #  echo "-------------------------------------------------------------------------" >> tout.txt
           done < errors.txt
-
+          echo "" >> tout.txt
           echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
           echo "              WARNINGS IN ${{  github.event.inputs.file2compile }}.tex" >> tout.txt
           echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
+          touch warnings.txt
+          grep -E "__WARNING__" warningError.txt >> warnings.txt
+          while IFS= read -r line; do
+            # determine if this line has already been written. If not, then proceed
+            if [[ "$(grep -c $line tout.txt)" == 0 ]]; then
+              echo $line | sed 's/^[0-9]*__[A-Z]*__//' >> tout.txt
+              linenum=$(echo $line | sed 's/^\([0-9]*)\.*/\1/')
+              # remove this line from warningError.txt
+              sed -i "/$line/d" warningError.txt
+              if [[ $linenum > 0 ]]; then
+                 # look for other occurances of this line number in the file
+                 touch tmp.txt && grep -E "^$linenum__" warningError.txt >> tmp.txt
+                 while IFS= read -r ln; do
+                   echo $ln | sed 's/^[0-9]*__[A-Z]*__//' >> tout.txt
+                   # remove from warningError.txt
+                   sed -i "/$ln/d" warningError.txt
+                 done < tmp.txt
+                 # now look up the line in the .tex file and place underneath
+                 head -n $linenum ${{ github.event.inputs.file2compile }}.tex | tail -1 >> tout.txt
+              fi
+              echo "-------------------------------------------------------------------------" >> tout.txt
+            fi
+          done < warnings.txt
           echo "" >> tout.txt
           echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
           echo "              CITATION ISSUES IN ${{  github.event.inputs.file2compile }}.tex " >> tout.txt
           echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>" >> tout.txt
-          grep -E "^Package natbib Warning\: Citation" ${{ github.event.inputs.file2compile }}_full.log >> tout.txt
           touch referr.txt
-          grep -E "^Package natbib Warning\: Citation" ${{ github.event.inputs.file2compile }}_full.log >> referr.txt
+
           echo " "
           echo " "
           echo " "
