Update compileMyLatex.yml

diff --git a/.github/workflows/compileMyLatex.yml b/.github/workflows/compileMyLatex.yml
--- a/.github/workflows/compileMyLatex.yml
+++ b/.github/workflows/compileMyLatex.yml
@@ -297,6 +297,11 @@ jobs:
 
       - name: Capture full compilation output
         run: |
+           # ....... if the pdf file was generated, then the errors must have not been fatal.
+           noFatalErrors = false;
+           grep -Eq "output to '${PDFFILE}'"
+           if [[ "$(grep -Eq "output to '${PDFFILE}'" compileOut.txt)$?" == 0 ]]; then noFatalErrors=true; fi
+           echo "${noFatalErrors}"
            # ....... prepare the compilation log for processing by first removing all end-of-line characters
            touch errout.txt
            # ....... just to be safe, remove all \a, \t and \x0 because we use these as special markers later
@@ -367,6 +372,8 @@ jobs:
                   if [[ "${sorted[$j]}" =~ "-${errtypes[$i]}-" ]]; then 
                      issue="${sorted[$j]}"
                      if [[ "${errtypes[$i]}" =~ "ERROR" ]]; then touch thereAreErrors.txt; fi
+                     # if a pdf file was generated by the compiler, then consider the errors to not be fatal.
+                     
                      # ######################### TEMPORARY ###########################
                      rm -f thereAreErrors.txt
                      # ###############################################################
